### ISSUE TITLE
About kirk_init() rnd_seed

### ISSUE THREAD

**Issue by bucanero** [ProximaV/kirk-engine-full#3]
Probably not a big deal, but reviewing the code, I saw that `rnd_seed` is not used when calling `kirk_init2()`.
I think this code where `seed_size` is checked, was meant to use the `rnd_seed`?

https://github.com/ProximaV/kirk-engine-full/blob/5fbc3df193cbbe6fd2ce9db274893cd06a3dadbf/libkirk/kirk_engine.c#L915-L925

Something like:
```c
     seedbuf=(u8*)malloc(seed_size+4);
     memcpy(seedbuf + 4, rnd_seed, seed_size);
     seedheader= (KIRK_SHA1_HEADER *) seedbuf; 
     seedheader->data_size = seed_size; 
```

that way the `rnd_seed` would be used when calling CMD11 to generate `PRNG_DATA`.

If it makes sense I can open a PR, but wanted to confirm if it's the intended behavior or not.

**Comment by ProximaV** [comment]
Good catch. fixed.
